### ISSUE TITLE
Shoebill 2.0 in production

### ISSUE THREAD

**Issue by FranDevet** [Shoebill/ShoebillPlugin#12]
Is it recommended to use this version in production or would it be better to use the 1.3-SNAPSHOT branch?

**Comment by 123marvin123** [comment]
The Shoebill 2.0 version was not production ready, because it introduced a lot of behind-the-scene changes. You're better of with 1.3-SNAPSHOT

**Comment by FranDevet** [comment]
Thanks, I close this issue.
