### ISSUE TITLE
Server crashes when passing null strings

### ISSUE THREAD

**Issue by lleps** [Shoebill/ShoebillPlugin#4]
JNI functions do not check if given java objects are null.
When you pass null values, the server immediately crashes and creates a file "hs_err_pid<process id>.log" which contains native crash info.

For example, doing this on java:

``` java
player.playAudioStream(null);
```

crashes the server and creates the hs_err_.. file.

**Comment by 123marvin123** [comment]
Thanks for your report. I will investigate this issue.

What do you think should happen if the given object is null ?

**Comment by lleps** [comment]
Hi. I think it should throw a NPE to java code and return the function, something like this:

``` c++
void throwNPE(JNIEnv *env, char *param_name, char *function_name) {
    char buffer[512];
    sprintf(buffer, "Parameter '%s' in function '%s' cannot be null.", param_name, function_name);
    env->ThrowNew(env->FindClass("java/lang/NullPointerException"), buffer);
}

#define assertNotNull(obj,param_name,function_name); \
if(!obj) { throwNPE(env,param_name,function_name); return 0; }

JNI_PlayAudioStreamForPlayer(env, jstring *url) {
   assertNotNull(url, "url", __FUNCTION__);
}
```

So you can handle it directly in java code (and you know what went wrong)

**Comment by 123marvin123** [comment]
I will implement this, but this problem should not occur in Shoebill 2.0 anyways since Kotlin has safeguarding for such cases.
